package com.redhat.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.redhat.model.Store;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-06-15T14:18:39.847-03:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.rhmart.com/Stores/", name = "Stores")
@XmlSeeAlso({ObjectFactory.class})
public interface Stores {

    @WebMethod(action = "http://www.rhmart.com/Stores/createStore")
    @RequestWrapper(localName = "createStore", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.CreateStore")
    @ResponseWrapper(localName = "createStoreResponse", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.CreateStoreResponse")
    @WebResult(name = "response", targetNamespace = "")
    public java.lang.String createStore(
        @WebParam(name = "store", targetNamespace = "")
        Store store
    );

    @WebMethod(action = "http://www.rhmart.com/Stores/deleteStore")
    @RequestWrapper(localName = "deleteStore", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.DeleteStore")
    @ResponseWrapper(localName = "deleteStoreResponse", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.DeleteStoreResponse")
    @WebResult(name = "response", targetNamespace = "")
    public java.lang.String deleteStore(
        @WebParam(name = "storeID", targetNamespace = "")
        int storeID
    );

    @WebMethod(action = "http://www.rhmart.com/Stores/getStore")
    @RequestWrapper(localName = "getStore", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.GetStore")
    @ResponseWrapper(localName = "getStoreResponse", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.GetStoreResponse")
    @WebResult(name = "store", targetNamespace = "")
    public Store getStore(
        @WebParam(name = "storeID", targetNamespace = "")
        int storeID
    );

    @WebMethod(action = "http://www.rhmart.com/Stores/getAllStores")
    @RequestWrapper(localName = "getAllStores", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.GetAllStores")
    @ResponseWrapper(localName = "getAllStoresResponse", targetNamespace = "http://www.rhmart.com/Stores/", className = "com.redhat.service.GetAllStoresResponse")
    @WebResult(name = "Stores", targetNamespace = "")
    public com.redhat.service.StoresType getAllStores();
}
